export {default as Home} from './home'
export {default as Auth} from './auth'
export {default as Rated} from './rated'
export {default as MovieDetails} from './movie-details'
export {default as TvShowDetails} from './tvshow-details'
export {default as NotFound} from './not-found'